"""empty message

Revision ID: 50bff4f96242
Revises: 76a556cd627c
Create Date: 2025-10-08 15:47:01.955848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50bff4f96242'
down_revision = '76a556cd627c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
